import { isSupabaseConfigured, supabase } from './supabase'

export type CirclePostType='question'|'help_request'|'resource'|'progress_update'|'project_feedback'
export type CircleMembership='active'|'pending'|undefined
export type CircleSummary={id:string;name:string;description:string;category:string;circleType:'skill'|'goal'|'project'|'language'|'location';language:string;tags:string[];rules:string[];joinMode:'public'|'request';activityLevel:'New'|'Quiet'|'Active'|'Very active';memberCount:number;weeklyPosts:number;memberLimit:number;createdAt:string;coverUrl?:string;isMember:boolean;membershipStatus:CircleMembership;relevanceScore:number}
export type CircleMember={id:string;name:string;avatarUrl?:string;headline?:string;reputationLabel:string;role?:string}
export type CircleReply={id:string;body:string;createdAt:string;author:{id:string;name:string;avatarUrl?:string}}
export type CirclePost={id:string;type:CirclePostType;title:string;body:string;skillTag?:string;createdAt:string;author:{id:string;name:string;avatarUrl?:string;reputationLabel?:string};helpfulCount:number;hasHelpful:boolean;replies:CircleReply[]}
export type CircleRitual={id:string;title:string;description:string;cadence:string;prompt:string}
export type CircleDetail={circle:CircleSummary&{isOwner?:boolean};members:CircleMember[];posts:CirclePost[];rituals:CircleRitual[];recommendedMembers:CircleMember[]}
export type CircleWorkspace={circles:CircleSummary[];categories:string[]}
export type CreateCircleInput={name:string;category:string;description:string;circleType:CircleSummary['circleType'];language:string;tags:string[];rules:string[];joinMode:'public'|'request';memberLimit:number;coverUrl?:string}

const seeds:CircleSummary[]=[
  {id:'english-practice',name:'English Speaking Practice',description:'Friendly weekly practice for people who want to speak with more confidence, not chase perfect grammar.',category:'Languages',circleType:'language',language:'English',tags:['English','Speaking','Confidence'],rules:['Give everyone room to speak','Correct kindly and only when helpful'],joinMode:'public',activityLevel:'Very active',memberCount:206,weeklyPosts:34,memberLimit:300,createdAt:'2026-03-12T10:00:00Z',isMember:true,membershipStatus:'active',relevanceScore:96},
  {id:'react-native-beginners',name:'React Native Beginners',description:'Build your first useful mobile app alongside people solving the same practical problems.',category:'Coding',circleType:'skill',language:'English',tags:['React Native','Expo','Mobile'],rules:['Share reproducible examples','Explain the why, not only the fix'],joinMode:'public',activityLevel:'Very active',memberCount:84,weeklyPosts:29,memberLimit:150,createdAt:'2026-04-04T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:92},
  {id:'ui-feedback',name:'UI/UX Feedback Club',description:'A focused critique room for screens, flows, prototypes, and the decisions behind them.',category:'Design',circleType:'project',language:'English',tags:['UI Design','UX','Feedback'],rules:['Critique the work, never the person','Make every comment actionable'],joinMode:'request',activityLevel:'Active',memberCount:128,weeklyPosts:22,memberLimit:180,createdAt:'2026-01-20T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:89},
  {id:'moroccan-english',name:'Moroccan Students Learning English',description:'A Darija-friendly community for Moroccan students building everyday English confidence together.',category:'Local community',circleType:'location',language:'English',tags:['Morocco','Students','English'],rules:['Darija is welcome when it helps','Keep practice welcoming'],joinMode:'public',activityLevel:'Active',memberCount:173,weeklyPosts:18,memberLimit:250,createdAt:'2026-05-16T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:86},
  {id:'portfolio-review',name:'Portfolio Review Circle',description:'Get specific feedback on case studies, positioning, presentation, and the story your work tells.',category:'Career',circleType:'project',language:'English',tags:['Portfolio','Career','Feedback'],rules:['Say what is already working','Be specific about the next improvement'],joinMode:'public',activityLevel:'Active',memberCount:67,weeklyPosts:15,memberLimit:100,createdAt:'2026-06-12T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:79},
  {id:'ai-creators',name:'AI Tools for Creators',description:'Trade practical workflows for research, visuals, writing, and production without the hype.',category:'AI tools',circleType:'skill',language:'English',tags:['AI','Creators','Workflow'],rules:['Share what you actually tested','Label generated work honestly'],joinMode:'public',activityLevel:'Very active',memberCount:241,weeklyPosts:41,memberLimit:350,createdAt:'2026-02-08T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:75},
  {id:'startup-builders',name:'Startup Builders',description:'A small accountability loop for founders shipping, testing, and helping each other make clearer decisions.',category:'Business',circleType:'goal',language:'English',tags:['Startups','MVP','Growth'],rules:['Bring real decisions','No unsolicited promotion'],joinMode:'request',activityLevel:'Active',memberCount:93,weeklyPosts:19,memberLimit:120,createdAt:'2026-05-01T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:72},
  {id:'logo-critique',name:'Logo Design Critique',description:'Thoughtful critique for identity concepts, marks, typography, and real brand applications.',category:'Design',circleType:'project',language:'French',tags:['Logo Design','Branding','Typography'],rules:['Ask about the brief first','Avoid taste-only feedback'],joinMode:'public',activityLevel:'New',memberCount:31,weeklyPosts:8,memberLimit:80,createdAt:'2026-06-18T10:00:00Z',isMember:false,membershipStatus:undefined,relevanceScore:68},
]

const members:CircleMember[]=[
  {id:'sara',name:'Sara Amrani',headline:'React Native developer',reputationLabel:'Reliable Helper',role:'moderator'},
  {id:'yassine',name:'Yassine Karim',headline:'English practice partner',reputationLabel:'Great Explainer',role:'member'},
  {id:'lina',name:'Lina Haddad',headline:'Product designer',reputationLabel:'Project Fixer',role:'member'},
  {id:'omar',name:'Omar Benali',headline:'Patient peer mentor',reputationLabel:'Friendly Mentor',role:'member'},
]
const rituals:CircleRitual[]=[
  {id:'weekly-feedback',title:'Weekly feedback thread',description:'Give one useful piece of feedback and ask for one.',cadence:'Every Monday',prompt:'Share something you are improving this week.'},
  {id:'find-partner',title:'Find a partner',description:'Pair up for a focused practice exchange.',cadence:'Every Wednesday',prompt:'What can you practice together for 30 minutes?'},
  {id:'share-progress',title:'Share your progress',description:'Make small wins visible and keep momentum.',cadence:'Every Friday',prompt:'What moved forward since your last check-in?'},
  {id:'quick-help',title:'Ask for quick help',description:'Unblock one specific question together.',cadence:'Anytime',prompt:'What is the smallest useful answer you need?'},
]
const seedPosts:Record<string,CirclePost[]>={
  'english-practice':[
    {id:'post-1',type:'help_request',title:'Practice partner for a 20-minute call?',body:'I have an interview next week and want to practice introducing myself without translating in my head. Evening works best.',skillTag:'Speaking confidence',createdAt:'2026-06-20T09:10:00Z',author:{id:'sara',name:'Sara Amrani',reputationLabel:'Reliable Helper'},helpfulCount:18,hasHelpful:false,replies:[{id:'reply-1',body:'I can practice tonight and share the questions that helped me.',createdAt:'2026-06-20T09:32:00Z',author:{id:'omar',name:'Omar Benali'}}]},
    {id:'post-2',type:'progress_update',title:'First full meeting in English',body:'I led our stand-up today. I paused a few times, but I did not switch languages. The weekly practice is working.',skillTag:'Progress',createdAt:'2026-06-19T17:00:00Z',author:{id:'yassine',name:'Yassine Karim',reputationLabel:'Great Explainer'},helpfulCount:31,hasHelpful:true,replies:[]},
    {id:'post-3',type:'question',title:'How do you make corrections feel natural?',body:'When you practice with a partner, do you correct mistakes immediately or collect them for the end?',skillTag:'Peer feedback',createdAt:'2026-06-18T13:15:00Z',author:{id:'lina',name:'Lina Haddad',reputationLabel:'Project Fixer'},helpfulCount:12,hasHelpful:false,replies:[]},
  ],
}

const customKey='skillloop_preview_circles',membershipKey='skillloop_preview_circle_memberships',postsKey='skillloop_preview_circle_posts',repliesKey='skillloop_preview_circle_replies',helpfulKey='skillloop_preview_circle_helpful'
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
function write(key:string,value:unknown){localStorage.setItem(key,JSON.stringify(value))}
function previewCircles(){const custom=read<CircleSummary[]>(customKey,[]),membership=read<Record<string,CircleMembership|null>>(membershipKey,{});return [...custom,...seeds].map(circle=>{const overridden=Object.prototype.hasOwnProperty.call(membership,circle.id),status=overridden?membership[circle.id]||undefined:circle.membershipStatus,memberDelta=status==='active'&&!circle.isMember?1:status!=='active'&&circle.isMember?-1:0;return{...circle,memberCount:circle.memberCount+memberDelta,membershipStatus:status,isMember:status==='active'}})}
function previewPosts(circleId:string){const added=read<Record<string,CirclePost[]>>(postsKey,{}),replies=read<Record<string,CircleReply[]>>(repliesKey,{}),helpful=read<Record<string,boolean>>(helpfulKey,{});return [...(added[circleId]||[]),...(seedPosts[circleId]||[])].map(post=>({...post,replies:[...post.replies,...(replies[post.id]||[])],hasHelpful:helpful[post.id]??post.hasHelpful,helpfulCount:post.helpfulCount+(helpful[post.id]===true&&!post.hasHelpful?1:helpful[post.id]===false&&post.hasHelpful?-1:0)}))}

export async function loadCirclesWorkspace():Promise<CircleWorkspace>{if(!isSupabaseConfigured){const circles=previewCircles();return{circles,categories:[...new Set(circles.map(circle=>circle.category))].sort()}}const{data,error}=await supabase.rpc('get_circles_workspace');if(error)throw error;return data as CircleWorkspace}
export async function loadCircleDetail(id:string):Promise<CircleDetail>{if(!isSupabaseConfigured){const circle=previewCircles().find(item=>item.id===id);if(!circle)throw new Error('Circle not found.');return{circle:{...circle,isOwner:read<CircleSummary[]>(customKey,[]).some(item=>item.id===id)},members,posts:previewPosts(id),rituals,recommendedMembers:members.slice(0,3)}}const{data,error}=await supabase.rpc('get_circle_detail',{target_circle:id});if(error)throw error;if(!data)throw new Error('Circle not found.');return data as CircleDetail}
export async function createLearningCircle(input:CreateCircleInput){if(!isSupabaseConfigured){const id=`circle-${crypto.randomUUID()}`,circle:CircleSummary={...input,id,activityLevel:'New',memberCount:1,weeklyPosts:0,createdAt:new Date().toISOString(),isMember:true,membershipStatus:'active',relevanceScore:100};write(customKey,[circle,...read<CircleSummary[]>(customKey,[])]);return id}const{data,error}=await supabase.rpc('create_learning_circle',{payload:{...input,circle_type:input.circleType,join_mode:input.joinMode,member_limit:input.memberLimit,cover_url:input.coverUrl||''}});if(error)throw error;return data as string}
export async function joinCircle(id:string,mode:'public'|'request'):Promise<CircleMembership>{if(!isSupabaseConfigured){const next=mode==='request'?'pending':'active',state=read<Record<string,CircleMembership|null>>(membershipKey,{});state[id]=next;write(membershipKey,state);return next}const{data,error}=await supabase.rpc('join_learning_circle',{target_circle:id});if(error)throw error;return data as CircleMembership}
export async function leaveCircle(id:string){if(!isSupabaseConfigured){const state=read<Record<string,CircleMembership|null>>(membershipKey,{});state[id]=null;write(membershipKey,state);return}const{error}=await supabase.rpc('leave_learning_circle',{target_circle:id});if(error)throw error}
export async function createCirclePost(circleId:string,input:{type:CirclePostType;title:string;body:string;skillTag:string},authorName:string){if(!isSupabaseConfigured){const all=read<Record<string,CirclePost[]>>(postsKey,{}),post:CirclePost={id:crypto.randomUUID(),...input,createdAt:new Date().toISOString(),author:{id:'preview',name:authorName,reputationLabel:'Growing Helper'},helpfulCount:0,hasHelpful:false,replies:[]};all[circleId]=[post,...(all[circleId]||[])];write(postsKey,all);return post.id}const{data,error}=await supabase.rpc('create_circle_post',{target_circle:circleId,kind:input.type,post_title:input.title,post_body:input.body,tag:input.skillTag});if(error)throw error;return data as string}
export async function replyToCirclePost(postId:string,body:string,authorName:string){if(!isSupabaseConfigured){const all=read<Record<string,CircleReply[]>>(repliesKey,{}),reply:CircleReply={id:crypto.randomUUID(),body,createdAt:new Date().toISOString(),author:{id:'preview',name:authorName}};all[postId]=[...(all[postId]||[]),reply];write(repliesKey,all);return reply.id}const{data,error}=await supabase.rpc('reply_to_circle_post',{target_post:postId,reply_body:body});if(error)throw error;return data as string}
export async function togglePostHelpful(postId:string,current:boolean){if(!isSupabaseConfigured){const all=read<Record<string,boolean>>(helpfulKey,{});all[postId]=!current;write(helpfulKey,all);return!current}const{data,error}=await supabase.rpc('toggle_circle_post_helpful',{target_post:postId});if(error)throw error;return Boolean(data)}
export async function reportCircleContent(postId?:string,replyId?:string,details=''){if(!isSupabaseConfigured){const reports=read<unknown[]>('skillloop_preview_circle_reports',[]);write('skillloop_preview_circle_reports',[...reports,{postId,replyId,details,createdAt:new Date().toISOString()}]);return}const{error}=await supabase.rpc('report_circle_content',{target_post:postId||null,target_reply:replyId||null,report_reason:'Community guidelines',report_details:details});if(error)throw error}
