import { isSupabaseConfigured, supabase } from './supabase'
import type { RequestKind } from './exchange'

export type SessionContext={id:string;status:'scheduled'|'in_progress'|'completed'|'cancelled'|'disputed';skill:string;offeredSkill?:string;requestType:RequestKind;format:string;startsAt:string;duration:number;creditCost:number;learnerId:string;helperId:string;learnerConfirmed:boolean;helperConfirmed:boolean}
export type Conversation={id:string;partnerId:string;partnerName:string;partnerAvatar?:string;lastMessage:string;lastMessageAt:string;unreadCount:number;session?:SessionContext}
export type ChatMessage={id:string;senderId?:string;senderName?:string;type:'text'|'system';body:string;readAt?:string;createdAt:string}
export type Preparation={notes:string;projectLink:string;checklist:string[]}
export type SessionRecord=SessionContext&{learnerName:string;helperName:string;skillId:string;attachmentUrl?:string;meetingUrl?:string;conversationId?:string;myPreparation?:Preparation;hasReviewed:boolean}
export type AppNotification={id:string;type:string;title:string;body:string;actionUrl?:string;readAt?:string;createdAt:string}

const previewMessagesKey=(id:string)=>`skillloop_preview_messages_${id}`
const previewConversationsKey='skillloop_preview_conversations',previewSessionsKey='skillloop_preview_sessions',previewNotificationsKey='skillloop_preview_notifications'
function readPreview<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'')as T}catch{return fallback}}
function writePreview(key:string,value:unknown){localStorage.setItem(key,JSON.stringify(value))}
export async function loadConversations():Promise<Conversation[]>{if(!isSupabaseConfigured)return readPreview<Conversation[]>(previewConversationsKey,[]);const{data,error}=await supabase.rpc('get_chat_workspace');if(error)throw error;return(data||[])as Conversation[]}
export async function loadMessages(conversationId:string):Promise<ChatMessage[]>{if(!isSupabaseConfigured){try{return JSON.parse(localStorage.getItem(previewMessagesKey(conversationId))||'[]')}catch{return[]}}const{data,error}=await supabase.rpc('get_conversation_messages',{target_conversation:conversationId});if(error)throw error;return(data||[])as ChatMessage[]}
export async function sendMessage(conversationId:string,body:string,userId?:string){if(!body.trim())throw new Error('Write a message before sending.');if(!isSupabaseConfigured){const rows=await loadMessages(conversationId),message:ChatMessage={id:crypto.randomUUID(),senderId:userId||'preview',senderName:'You',type:'text',body:body.trim(),createdAt:new Date().toISOString()};localStorage.setItem(previewMessagesKey(conversationId),JSON.stringify([...rows,message]));writePreview(previewConversationsKey,readPreview<Conversation[]>(previewConversationsKey,[]).map(item=>item.id===conversationId?{...item,lastMessage:message.body,lastMessageAt:message.createdAt,unreadCount:0}:item));return message}const{data,error}=await supabase.rpc('send_chat_message',{target_conversation:conversationId,content:body});if(error)throw error;return data}
export async function markConversationRead(conversationId:string){if(!isSupabaseConfigured)return;await supabase.rpc('mark_conversation_read',{target_conversation:conversationId})}
export function subscribeToMessages(conversationId:string,onMessage:(message:ChatMessage)=>void){if(!isSupabaseConfigured)return()=>{};const channel=supabase.channel(`messages:${conversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},payload=>{const row=payload.new as Record<string,unknown>;onMessage({id:String(row.id),senderId:row.sender_id?String(row.sender_id):undefined,type:row.message_type as 'text'|'system',body:String(row.body),readAt:row.read_at?String(row.read_at):undefined,createdAt:String(row.created_at)})}).subscribe();return()=>{supabase.removeChannel(channel)}}

export async function loadSessions():Promise<SessionRecord[]>{if(!isSupabaseConfigured)return readPreview<SessionRecord[]>(previewSessionsKey,[]);const{data,error}=await supabase.rpc('get_sessions_workspace');if(error)throw error;return(data||[])as SessionRecord[]}
export async function updateSchedule(id:string,start:string,duration:number,format:string){if(!isSupabaseConfigured){if(new Date(start).getTime()<Date.now())throw new Error('Choose a future session time.');writePreview(previewSessionsKey,readPreview<SessionRecord[]>(previewSessionsKey,[]).map(item=>item.id===id?{...item,startsAt:start,duration,format}:item));return}const{error}=await supabase.rpc('update_session_schedule',{target_session:id,new_start:start,new_duration:duration,new_format:format});if(error)throw error}
export async function startLearningSession(id:string){if(!isSupabaseConfigured){const rows=readPreview<SessionRecord[]>(previewSessionsKey,[]);const session=rows.find(item=>item.id===id);if(!session||session.status!=='scheduled')throw new Error('This session cannot be started.');writePreview(previewSessionsKey,rows.map(item=>item.id===id?{...item,status:'in_progress'}:item));return}const{error}=await supabase.rpc('start_session',{target_session:id});if(error)throw error}
export async function savePreparation(id:string,preparation:Preparation){if(!isSupabaseConfigured){localStorage.setItem(`skillloop_preparation_${id}`,JSON.stringify(preparation));return}const{error}=await supabase.rpc('save_session_preparation',{target_session:id,preparation:{notes:preparation.notes,project_link:preparation.projectLink,checklist:preparation.checklist}});if(error)throw error}
export async function submitReview(id:string,rating:number,tags:string[],comment:string,exchangeAgain:boolean){if(rating<1||rating>5)throw new Error('Choose a rating from 1 to 5.');if(comment.trim().length<10)throw new Error('Add a short written review with at least 10 characters.');if(!isSupabaseConfigured){const key=`skillloop_review_${id}`;if(localStorage.getItem(key))throw new Error('You already reviewed this session.');const sessions=readPreview<SessionRecord[]>(previewSessionsKey,[]),session=sessions.find(item=>item.id===id);if(!session||session.status!=='completed')throw new Error('Reviews open after a completed exchange.');localStorage.setItem(key,JSON.stringify({rating,tags,comment:comment.trim(),exchangeAgain}));writePreview(previewSessionsKey,sessions.map(item=>item.id===id?{...item,hasReviewed:true}:item));return}const{error}=await supabase.rpc('submit_session_review',{target_session:id,stars:rating,review_tags:tags,review_text:comment,exchange_again:exchangeAgain});if(error)throw error}

export async function loadNotifications():Promise<AppNotification[]>{if(!isSupabaseConfigured)return readPreview<AppNotification[]>(previewNotificationsKey,[]);const{data,error}=await supabase.from('notifications').select('id,type,title,body,action_url,read_at,created_at').order('created_at',{ascending:false}).limit(30);if(error)throw error;return(data||[]).map(row=>({id:row.id,type:row.type,title:row.title,body:row.body,actionUrl:row.action_url||undefined,readAt:row.read_at||undefined,createdAt:row.created_at}))}
export async function markNotification(id:string){if(!isSupabaseConfigured){writePreview(previewNotificationsKey,readPreview<AppNotification[]>(previewNotificationsKey,[]).map(item=>item.id===id?{...item,readAt:new Date().toISOString()}:item));return}await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id)}
export function subscribeToNotifications(userId:string|undefined,onNotification:(item:AppNotification)=>void){if(!isSupabaseConfigured||!userId)return()=>{};const channel=supabase.channel(`notifications:${userId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${userId}`},payload=>{const row=payload.new as Record<string,unknown>;onNotification({id:String(row.id),type:String(row.type),title:String(row.title),body:String(row.body),actionUrl:row.action_url?String(row.action_url):undefined,createdAt:String(row.created_at)})}).subscribe();return()=>{supabase.removeChannel(channel)}}
