import { isSupabaseConfigured, supabase } from './supabase'
import { loadLocalProfile } from './skillProfile'
import { loadSkillPassport, type SkillPassport } from './passport'

export type ActivationChecklist={teachSkill:boolean;learnSkill:boolean;sentRequest:boolean;joinedCircle:boolean;completedExchange:boolean}
export type PublicRequestSummary={id:string;slug:string;neededSkill:string;offeredSkill?:string;message:string;status:'active'|'closed';views:number;createdAt:string}
export type GrowthWorkspace={username:string;referralCode:string;activated:boolean;activatedAt?:string;checklist:ActivationChecklist;referrals:{joined:number;rewarded:number;creditsEarned:number};publicRequests:PublicRequestSummary[]}
export type PublicHelpRequest={id:string;slug:string;neededSkill:string;offeredSkill?:string;message:string;createdAt:string;owner:{id:string;name:string;username:string;avatarUrl?:string;bio:string;reputationLabel:string;sessions:number}}

const growthKey='skillloop_preview_growth',helpKey='skillloop_preview_public_help'
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
function previewCode(){const existing=localStorage.getItem('skillloop_preview_referral_code');if(existing)return existing;const code=`LOOP${crypto.randomUUID().replaceAll('-','').slice(0,6).toUpperCase()}`;localStorage.setItem('skillloop_preview_referral_code',code);return code}
export async function loadGrowthWorkspace(userId?:string,fallbackName?:string):Promise<GrowthWorkspace>{if(!isSupabaseConfigured){const profile=loadLocalProfile(userId,fallbackName),requests=read<{status:string}[]>('skillloop_preview_requests',[]),circleMemberships=read<Record<string,string|null>>('skillloop_preview_circle_memberships',{}),stored=read<Partial<GrowthWorkspace>>(growthKey,{}),checklist={teachSkill:profile.teach.length>0,learnSkill:profile.learn.length>0,sentRequest:requests.length>0,joinedCircle:Object.values(circleMemberships).includes('active')||Boolean(stored.checklist?.joinedCircle),completedExchange:profile.progress.sessions>0};return{username:stored.username||`${profile.full_name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'member'}-demo`,referralCode:previewCode(),activated:Object.values(checklist).slice(2).some(Boolean),checklist,referrals:stored.referrals||{joined:0,rewarded:0,creditsEarned:0},publicRequests:read<PublicRequestSummary[]>(helpKey,[])}}const{data,error}=await supabase.rpc('get_growth_workspace');if(error)throw error;return data as GrowthWorkspace}
export async function applyReferral(code:string){if(!code)return false;if(!isSupabaseConfigured){if(localStorage.getItem('skillloop_preview_referral_applied'))return false;localStorage.setItem('skillloop_preview_referral_applied',code);return true}const{data,error}=await supabase.rpc('apply_referral',{code});if(error)throw error;return Boolean(data)}
export async function createPublicHelpRequest(neededSkill:string,offeredSkill:string,message:string,ownerName:string){if(!isSupabaseConfigured){const slug=`${neededSkill.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${crypto.randomUUID().slice(0,8)}`,rows=read<PublicRequestSummary[]>(helpKey,[]),item:PublicRequestSummary={id:crypto.randomUUID(),slug,neededSkill,offeredSkill:offeredSkill||undefined,message,status:'active',views:0,createdAt:new Date().toISOString()};localStorage.setItem(helpKey,JSON.stringify([item,...rows]));localStorage.setItem(`skillloop_preview_help_${slug}`,JSON.stringify({...item,owner:{id:'preview',name:ownerName,username:'preview-member',bio:'A curious learner exchanging useful skills.',reputationLabel:'Growing Helper',sessions:0}}));return slug}const{data,error}=await supabase.rpc('create_public_help_request',{needed:neededSkill,offered:offeredSkill,content:message});if(error)throw error;return data as string}
export async function loadPublicHelpRequest(slug:string):Promise<PublicHelpRequest>{if(!isSupabaseConfigured){const item=read<PublicHelpRequest|null>(`skillloop_preview_help_${slug}`,null);if(item)return item;return{id:'preview-help',slug,neededSkill:'React Native',offeredSkill:'UI Design',message:'I am building my first mobile app and need focused help with navigation. I can offer a practical UI review in return.',createdAt:new Date().toISOString(),owner:{id:'preview',name:'Adam',username:'adam-demo',bio:'Designer learning to build useful mobile products.',reputationLabel:'Growing Helper',sessions:4}}}const{data,error}=await supabase.rpc('get_public_help_request',{request_slug:slug});if(error)throw error;if(!data)throw new Error('This help request is no longer active.');return data as PublicHelpRequest}
export async function loadPublicPassport(username:string):Promise<SkillPassport>{if(!isSupabaseConfigured)return loadSkillPassport(undefined,username.split('-').map(v=>v[0]?.toUpperCase()+v.slice(1)).join(' '));const{data,error}=await supabase.rpc('get_public_passport',{public_username:username});if(error)throw error;if(!data)throw new Error('This Skill Passport could not be found.');return data as SkillPassport}
