import { isSupabaseConfigured, supabase } from './supabase'
import { loadLocalProfile } from './skillProfile'

export type PassportBadge={id:string;name:string;slug:string;description:string;icon:string;unlocked:boolean;awardedAt?:string}
export type PassportReview={id:string;reviewer:string;rating:number;tags:string[];comment:string;exchangeAgain:boolean;createdAt:string}
export type SkillPassport={profile:{id?:string;name:string;bio:string;avatarUrl:string;languages:string[];timezone:string;rating:number;responseRate:number;noShowRate:number;reputationLabel:string;sessions:number};goal:string;teach:{id:string;name:string;level:string;formats:string[];verifiedReviews:number}[];learn:{id:string;name:string;level:string;goal:string;completed:boolean}[];creditsEarned:number;reviews:PassportReview[];badges:PassportBadge[];timeline:{type:'session'|'badge';title:string;date:string;meta:string}[]}
const badgeSeeds=[['First Exchange','first-exchange','Complete your first confirmed learning exchange.','heart-handshake'],['5 Sessions Completed','five-sessions','Show up and complete five learning sessions.','calendar-check'],['Great Explainer','great-explainer','Receive repeated praise for clear explanations.','lightbulb'],['Reliable Helper','reliable-helper','Build a record of reliable sessions.','shield-check'],['Skill Builder','skill-builder','Mark three learning skills as improved.','blocks'],['Project Reviewer','project-reviewer','Complete a project review as the helper.','file-check'],['Language Partner','language-partner','Complete a learning-partner exchange.','languages'],['Community Starter','community-starter','Create your first Learning Circle.','users']]
export async function loadSkillPassport(targetUser?:string,fallbackName?:string):Promise<SkillPassport>{
  if(isSupabaseConfigured){const{data,error}=await supabase.rpc('get_skill_passport',{target_user:targetUser||null});if(error)throw error;return data as SkillPassport}
  const profile=loadLocalProfile(targetUser,fallbackName),sessions=profile.progress.sessions
  return{profile:{id:targetUser,name:profile.full_name,bio:profile.bio,avatarUrl:profile.avatar_url,languages:profile.languages,timezone:profile.timezone,rating:profile.teach[0]?.rating||0,responseRate:100,noShowRate:0,reputationLabel:sessions?'Growing Helper':'New to the Loop',sessions},goal:profile.goal,teach:profile.teach.map(skill=>({id:skill.id||skill.name,name:skill.name,level:skill.level,formats:[skill.format],verifiedReviews:0})),learn:profile.learn.map(skill=>({id:skill.id||skill.name,name:skill.name,level:skill.level,goal:skill.goal||'',completed:Boolean(skill.completed)})),creditsEarned:profile.credits.earned,reviews:profile.reviews.map(review=>({...review,tags:[],exchangeAgain:true,createdAt:new Date().toISOString()})),badges:badgeSeeds.map(([name,slug,description,icon],index)=>({id:slug,name,slug,description,icon,unlocked:sessions>=(index===0?1:index===1?5:999)})),timeline:[]}
}
