import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, BadgeCheck, Ban, BookOpen, Check, CircleDollarSign, Clock3, Coins, Eye, FileWarning, Flag, History, LoaderCircle, MessageSquareWarning, RefreshCw, Search, ShieldCheck, ShieldOff, Star, Trash2, UserCheck, UserRound, UsersRound, X } from 'lucide-react'
import { loadAdminUserDetail, loadAdminWorkspace, moderate, type AdminReport, type AdminUser, type AdminUserDetail, type AdminWorkspace } from '../lib/admin'

type Tab='overview'|'users'|'reports'|'disputes'|'credits'|'content'|'skills'
const tabs:[Tab,string][]=[['overview','Overview'],['users','Users'],['reports','Reports'],['disputes','Disputes'],['credits','Credits'],['content','Content'],['skills','Skills']]
const ago=(value:string)=>new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value))
const tabFromPath=():Tab=>{const segment=window.location.pathname.split('/')[2];if(segment==='circles')return'content';return tabs.some(([value])=>value===segment)?segment as Tab:'overview'}

export function AdminPage(){
  const[data,setData]=useState<AdminWorkspace|null>(null),[tab,setTab]=useState<Tab>(tabFromPath),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[working,setWorking]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selectedUser,setSelectedUser]=useState<AdminUserDetail|null>(null)
  async function refresh(){setError('');try{setData(await loadAdminWorkspace())}catch(err){setError(err instanceof Error?err.message:'Could not load the admin workspace.')}finally{setLoading(false)}}
  useEffect(()=>{let live=true;loadAdminWorkspace().then(value=>{if(live)setData(value)}).catch(err=>{if(live)setError(err instanceof Error?err.message:'Could not load the admin workspace.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[])
  async function action(name:string,type:string,id:string,destructive=false){if(destructive&&!window.confirm('This moderation action changes user-visible data. Continue?'))return;const note=window.prompt('Add an internal note for the audit log (optional):')??'';setWorking(`${name}:${id}`);try{await moderate(name,type,id,note);setNotice('Moderation action completed and added to the audit log.');await refresh();if(selectedUser&&type==='user')setSelectedUser(await loadAdminUserDetail(id))}catch(err){setError(err instanceof Error?err.message:'Moderation action failed.')}finally{setWorking('')}}
  async function inspect(user:AdminUser){setWorking(`inspect:${user.id}`);try{setSelectedUser(await loadAdminUserDetail(user.id))}catch(err){setError(err instanceof Error?err.message:'Could not inspect this user.')}finally{setWorking('')}}
  const users=useMemo(()=>data?.users.filter(user=>`${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]),reports=useMemo(()=>data?.reports.filter(report=>`${report.reporterName} ${report.reportedUserName} ${report.reason}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query])
  if(loading)return <section className="admin-loading"><ShieldCheck/><LoaderCircle className="spin"/><h1>Opening the safety workspace…</h1></section>
  if(!data)return <section className="admin-loading"><ShieldOff/><h1>Admin data unavailable.</h1><p>{error}</p><button onClick={refresh}><RefreshCw/> Retry</button></section>
  return <section className="admin-page"><header className="admin-header"><div><div className="eyebrow"><ShieldCheck/> Protected operator workspace</div><h1>Safety & moderation</h1><p>Review context, protect credits, and leave an accountable record for every decision.</p></div><aside><span><i/> Systems operational</span><button onClick={refresh}><RefreshCw/> Refresh queues</button></aside></header><nav className="admin-tabs">{tabs.map(([value,label])=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{label}{value==='reports'&&data.stats.openReports>0?<b>{data.stats.openReports}</b>:value==='disputes'&&data.stats.disputes>0?<b>{data.stats.disputes}</b>:null}</button>)}</nav>{notice&&<div className="admin-notice"><Check/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice"><X/></button></div>}{error&&<div className="admin-notice error"><AlertTriangle/>{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X/></button></div>}{tab==='overview'&&<AdminOverview data={data} setTab={setTab}/>} {tab==='users'&&<><AdminToolbar query={query} setQuery={setQuery} placeholder="Search name or email"/><UsersTable users={users} working={working} inspect={inspect} action={action}/></>}{tab==='reports'&&<><AdminToolbar query={query} setQuery={setQuery} placeholder="Search people or reasons"/><ReportsQueue reports={reports} working={working} action={action}/></>}{tab==='disputes'&&<DisputesQueue data={data} working={working} action={action}/>} {tab==='credits'&&<CreditsTable data={data}/>} {tab==='content'&&<ContentModeration data={data} working={working} action={action}/>} {tab==='skills'&&<SkillsTable data={data} working={working} action={action}/>} {selectedUser&&<UserDrawer detail={selectedUser} working={working} close={()=>setSelectedUser(null)} action={action}/>}</section>
}

function AdminToolbar({query,setQuery,placeholder}:{query:string;setQuery:(value:string)=>void;placeholder:string}){return <div className="admin-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={placeholder}/></label><span>Actions require an audit note and are enforced by admin-only database functions.</span></div>}
function AdminOverview({data,setTab}:{data:AdminWorkspace;setTab:(tab:Tab)=>void}){const metrics=[['Total users',data.stats.totalUsers,UsersRound,'blue'],['New this week',data.stats.newUsers,UserCheck,'mint'],['Active sessions',data.stats.activeSessions,Clock3,'yellow'],['Completed sessions',data.stats.completedSessions,Check,'mint'],['Open reports',data.stats.openReports,Flag,'red'],['Disputes',data.stats.disputes,AlertTriangle,'red'],['Credit transactions',data.stats.creditTransactions,Coins,'yellow'],['Active circles',data.stats.activeCircles,UsersRound,'violet']] as const;return <><div className="admin-metrics">{metrics.map(([label,value,Icon,tone])=><article className={tone} key={label}><span><Icon/></span><strong>{value.toLocaleString()}</strong><small>{label}</small></article>)}</div><div className="admin-overview-grid"><section><header><div><FileWarning/><span><h2>Priority reports</h2><p>Oldest open safety items that need a decision.</p></span></div><button onClick={()=>setTab('reports')}>Open queue <ArrowRight/></button></header>{data.reports.filter(item=>['open','reviewing'].includes(item.status)).slice(0,4).map(report=><article className="admin-priority-row" key={report.id}><span className={`risk risk-${report.reason==='harassment'||report.reason==='unsafe behavior'?'high':'medium'}`}>{report.reason}</span><div><strong>{report.reportedUserName}</strong><p>{report.details||`Reported ${report.contentType}`}</p></div><small>{ago(report.createdAt)}</small></article>)}</section><aside><header><History/><div><h2>Recent decisions</h2><p>Every operator action is recorded.</p></div></header>{data.audit.length?data.audit.slice(0,6).map(item=><article key={item.id}><i/><div><strong>{item.action.replaceAll('_',' ')}</strong><p>{item.adminName} · {item.targetType}</p></div><small>{ago(item.createdAt)}</small></article>):<div className="admin-audit-empty"><ShieldCheck/><strong>No actions in this workspace yet.</strong><p>The audit trail begins with the first moderation decision.</p></div>}</aside></div></>}

function UsersTable({users,working,inspect,action}:{users:AdminUser[];working:string;inspect:(user:AdminUser)=>void;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Trust</th><th>Activity</th><th>Credits</th><th>Safety</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><div className="admin-user-cell"><span>{user.name.split(' ').map(v=>v[0]).join('').slice(0,2)}</span><div><strong>{user.name}{user.verified&&<BadgeCheck/>}</strong><small>{user.email} · joined {ago(user.createdAt)}</small></div></div></td><td><strong>{user.rating||'New'}</strong><small>{user.sessions} sessions</small></td><td><span className={`admin-status ${user.status}`}>{user.status}</span><small>{user.role}</small></td><td><strong>{user.credits}</strong><small>available</small></td><td><strong className={user.reports>0?'danger-text':''}>{user.reports} reports</strong><small>{user.warnings} warnings</small></td><td><div className="admin-row-actions"><button onClick={()=>inspect(user)} disabled={working===`inspect:${user.id}`}><Eye/> View</button>{!user.verified&&<button onClick={()=>action('verify_user','user',user.id)}><BadgeCheck/> Verify</button>}{user.status==='active'?<button className="danger" onClick={()=>action('suspend_user','user',user.id,true)}><Ban/> Suspend</button>:<button onClick={()=>action('unsuspend_user','user',user.id)}><UserCheck/> Restore</button>}</div></td></tr>)}</tbody></table>{!users.length&&<div className="admin-empty"><UserRound/><h3>No users match that search.</h3></div>}</div>}

function ReportsQueue({reports,working,action}:{reports:AdminReport[];working:string;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){return <div className="admin-report-list">{reports.map(report=><article key={report.id}><header><span className={`risk ${['harassment','scam','unsafe behavior'].includes(report.reason)?'risk-high':'risk-medium'}`}>{report.reason}</span><span className={`admin-status ${report.status}`}>{report.status}</span><small>{ago(report.createdAt)}</small></header><div className="admin-report-people"><div><small>REPORTED BY</small><strong>{report.reporterName}</strong></div><ArrowRight/><div><small>REPORTED USER</small><strong>{report.reportedUserName}</strong></div><b>{report.contentType.replace('_',' ')}</b></div><blockquote>{report.details||'No additional context was provided.'}</blockquote><footer>{['open','reviewing'].includes(report.status)&&<><button onClick={()=>action('dismiss_report','report',report.id)}><X/> Dismiss</button><button onClick={()=>action('warn_user','user',report.reportedUserId)}><MessageSquareWarning/> Warn user</button><button className="danger" onClick={()=>action('remove_content','report',report.id,true)} disabled={report.contentType==='profile'||report.contentType==='session'||working===`remove_content:${report.id}`}><Trash2/> Remove content</button><button className="primary" onClick={()=>action('resolve_report','report',report.id)}><Check/> Resolve</button></>}</footer></article>)}</div>}

function DisputesQueue({data,working,action}:{data:AdminWorkspace;working:string;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){return <div className="admin-dispute-grid">{data.disputes.map(item=><article key={item.id}><header><span><AlertTriangle/></span><div><small>DISPUTED SESSION</small><h2>{item.skill}</h2></div><b>{item.creditCost} credit{item.creditCost===1?'':'s'} protected</b></header><div className="dispute-people"><span><small>LEARNER</small><strong>{item.learnerName}</strong></span><ArrowRight/><span><small>HELPER</small><strong>{item.helperName}</strong></span></div><blockquote>{item.requestMessage}</blockquote><div className="dispute-credit-line"><CircleDollarSign/><span><small>CREDIT STATUS</small><strong>{item.creditStatus||'pending escrow'}</strong></span><small>{ago(item.createdAt)}</small></div><footer><button className="refund" disabled={Boolean(working)} onClick={()=>action('refund_credits','session',item.id,true)}><RefreshCw/> Refund learner</button><button className="release" disabled={Boolean(working)} onClick={()=>action('release_credits','session',item.id,true)}><Coins/> Release to helper</button></footer></article>)}{!data.disputes.length&&<div className="admin-empty"><Check/><h3>No open disputes.</h3><p>All protected credit decisions are settled.</p></div>}</div>}

function CreditsTable({data}:{data:AdminWorkspace}){return <><div className="credit-safety-banner"><ShieldCheck/><div><h2>Credit integrity</h2><p>Large adjustments and unusual refunds are highlighted for manual inspection.</p></div><strong>{data.transactions.filter(item=>item.suspicious).length} flagged</strong></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Movement</th><th>Reason</th><th>Status</th><th>Balance</th><th>Date</th></tr></thead><tbody>{data.transactions.map(item=><tr className={item.suspicious?'suspicious':''} key={item.id}><td><strong>{item.userName}</strong></td><td><b className={item.amount>0?'credit-positive':'credit-negative'}>{item.amount>0?'+':''}{item.amount}</b><small>{item.type}</small></td><td>{item.reason}{item.suspicious&&<span className="risk risk-high">Review</span>}</td><td><span className={`admin-status ${item.status}`}>{item.status}</span></td><td>{item.balanceAfter}</td><td>{ago(item.createdAt)}</td></tr>)}</tbody></table></div></>}

function ContentModeration({data,working,action}:{data:AdminWorkspace;working:string;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){return <div className="admin-content-grid"><section><header><UsersRound/><div><h2>Learning circles</h2><p>Community ownership, members, and content volume.</p></div></header>{data.circles.map(circle=><article key={circle.id}><div><strong>{circle.name}</strong><small>Owned by {circle.ownerName}</small></div><span>{circle.members} members</span><span>{circle.posts} posts</span><button className="danger" disabled={Boolean(working)} onClick={()=>action('remove_circle','circle',circle.id,true)}><Trash2/> Remove</button></article>)}</section><section><header><Star/><div><h2>Reviews</h2><p>Remove reviews that violate trust guidelines.</p></div></header>{data.reviews.map(review=><article className={!review.public?'removed':''} key={review.id}><div><strong>{review.rating}/5 · {review.reviewerName}</strong><small>For {review.revieweeName} · {ago(review.createdAt)}</small><p>{review.comment||'No written review.'}</p></div><button className="danger" disabled={!review.public||Boolean(working)} onClick={()=>action('remove_review','review',review.id,true)}>{review.public?<><Trash2/> Remove</>:<><Check/> Removed</>}</button></article>)}</section></div>}

function SkillsTable({data,working,action}:{data:AdminWorkspace;working:string;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Skill</th><th>Category</th><th>Teachers</th><th>Learners</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.skills.map(skill=><tr key={skill.id}><td><strong>{skill.name}</strong></td><td>{skill.category}</td><td>{skill.teachers}</td><td>{skill.learners}</td><td><span className={`admin-status ${skill.active?'active':'suspended'}`}>{skill.active?'active':'hidden'}</span></td><td><button disabled={Boolean(working)} onClick={()=>action(skill.active?'deactivate_skill':'activate_skill','skill',skill.id,skill.active)}>{skill.active?<><ShieldOff/> Hide skill</>:<><Check/> Activate</>}</button></td></tr>)}</tbody></table></div>}

function UserDrawer({detail,working,close,action}:{detail:AdminUserDetail;working:string;close:()=>void;action:(name:string,type:string,id:string,destructive?:boolean)=>void}){const p=detail.profile;return <div className="admin-drawer-backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><aside className="admin-user-drawer"><header><span>{p.name.split(' ').map(value=>value[0]).join('').slice(0,2)}</span><div><small>USER SAFETY RECORD</small><h2>{p.name}</h2><p>Joined {ago(p.createdAt)}</p></div><button onClick={close} aria-label="Close user record"><X/></button></header><div className="drawer-trust"><span><strong>{p.status}</strong><small>Account</small></span><span><strong>{p.verified?'Verified':'Unverified'}</strong><small>Identity</small></span><span><strong>{p.warnings}</strong><small>Warnings</small></span></div><section><h3>Admin actions</h3><div className="drawer-actions">{!p.verified&&<button onClick={()=>action('verify_user','user',p.id)}><BadgeCheck/> Verify user</button>}<button onClick={()=>action('warn_user','user',p.id)}><MessageSquareWarning/> Send warning</button>{p.status==='active'?<button className="danger" onClick={()=>action('suspend_user','user',p.id,true)}><Ban/> Suspend</button>:<button onClick={()=>action('unsuspend_user','user',p.id)}><UserCheck/> Unsuspend</button>}</div></section><section><h3>Reports ({detail.reports.length})</h3>{detail.reports.length?detail.reports.map(item=><article className="drawer-record" key={item.id}><Flag/><div><strong>{item.reason}</strong><p>{item.details||'No context'}</p></div><span>{item.status}</span></article>):<p className="drawer-empty">No reports against this member.</p>}</section><section><h3>Sessions ({detail.sessions.length})</h3>{detail.sessions.map(item=><article className="drawer-record" key={item.id}><BookOpen/><div><strong>{item.skill} with {item.partner}</strong><p>{item.role} · {ago(item.startsAt)}</p></div><span>{item.status}</span></article>)}</section><section><h3>Credit history ({detail.transactions.length})</h3>{detail.transactions.map(item=><article className="drawer-record" key={item.id}><Coins/><div><strong>{item.amount>0?'+':''}{item.amount} · {item.reason}</strong><p>Balance {item.balanceAfter} · {ago(item.createdAt)}</p></div><span>{item.status}</span></article>)}</section>{working&&<div className="drawer-working"><LoaderCircle className="spin"/> Updating safety record…</div>}</aside></div>}
