import { ArrowLeft, ArrowRight, Check, KeyRound, LoaderCircle, Mail, Sparkles } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Logo } from '../components/Logo'
import { isSupabaseConfigured, supabase } from '../lib/supabase'

function AuthFrame({ children }: { children: React.ReactNode }) { return <main className="auth-support"><div className="auth-support-glow" /><div className="auth-support-card"><Logo />{children}<Link className="auth-back" to="/login"><ArrowLeft /> Back to login</Link></div><div className="auth-mini-card mini-teach"><span>UI</span><small>Teach</small><strong>Interface design</strong></div><div className="auth-mini-card mini-learn"><span>EN</span><small>Learn</small><strong>Confident English</strong></div></main> }

export function ForgotPasswordPage() {
  const [sent, setSent] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState('')
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(''); setLoading(true); const email = String(new FormData(e.currentTarget).get('email')); if (isSupabaseConfigured) { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); if (error) setError(error.message); else setSent(true) } else setSent(true); setLoading(false) }
  return <AuthFrame>{sent ? <div className="auth-support-content"><span className="auth-support-icon"><Check /></span><div className="eyebrow">Check your inbox</div><h1>Your reset link is on its way.</h1><p>Use the secure link in the email to choose a new password. It may take a minute to arrive.</p></div> : <div className="auth-support-content"><span className="auth-support-icon"><Mail /></span><div className="eyebrow">Password recovery</div><h1>Let’s get you back in.</h1><p>Enter the email connected to your SkillLoop account.</p><form onSubmit={submit}><label>Email address<input type="email" name="email" placeholder="you@example.com" required /></label>{error && <div className="form-message">{error}</div>}<button className="button button-primary button-full" disabled={loading}>{loading ? 'Sending…' : 'Send reset link'}<ArrowRight /></button></form></div>}</AuthFrame>
}

export function ResetPasswordPage() {
  const [message,setMessage]=useState(''),[loading,setLoading]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),password=String(data.get('password')),confirm=String(data.get('confirm'));if(password.length<8||!/[A-Z]/.test(password)||!/[0-9]/.test(password))return setMessage('Use 8+ characters, one uppercase letter, and one number.');if(password!==confirm)return setMessage('Your passwords do not match.');setLoading(true);if(isSupabaseConfigured){const{error}=await supabase.auth.updateUser({password});setMessage(error?.message||'Password updated. You can now log in.')}else setMessage('Password updated. You can now log in.');setLoading(false)}
  return <AuthFrame><div className="auth-support-content"><span className="auth-support-icon"><KeyRound /></span><div className="eyebrow">Choose a new password</div><h1>Make it memorable and strong.</h1><p>Use at least eight characters with an uppercase letter and a number.</p><form onSubmit={submit}><label>New password<input type="password" name="password" required /></label><label>Confirm password<input type="password" name="confirm" required /></label>{message&&<div className="form-message">{message}</div>}<button className="button button-primary button-full" disabled={loading}>Update password <ArrowRight /></button></form></div></AuthFrame>
}

export function AuthCallbackPage() { const navigate=useNavigate(); const [error,setError]=useState(''); useEffect(()=>{if(!isSupabaseConfigured){navigate('/onboarding',{replace:true});return}supabase.auth.getSession().then(({data,error})=>{if(error)setError(error.message);else navigate(data.session?'/onboarding':'/login',{replace:true})})},[navigate]); return <AuthFrame><div className="auth-support-content"><span className="auth-support-icon spin"><LoaderCircle /></span><div className="eyebrow"><Sparkles /> Secure sign in</div><h1>{error?'We could not finish signing you in.':'Opening your learning loop…'}</h1><p>{error||'Confirming your account and preparing your profile.'}</p></div></AuthFrame> }
