import { ArrowDownUp, ArrowRight, Award, CalendarDays, Check, Clock3, Coins, Compass, Filter, HeartHandshake, Languages, LoaderCircle, MessageCircle, Paperclip, Search, SlidersHorizontal, Sparkles, Star, Target, UserRound, UsersRound, Video, X, Zap } from 'lucide-react'
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { buildMatches, loadMatchCandidates, type MatchResult, type MatchType } from '../lib/matching'
import { loadLocalProfile, loadRemoteProfile, type SkillProfile } from '../lib/skillProfile'
import { createRequest, creditCost, requestTypeLabel, type RequestKind } from '../lib/exchange'
import { uploadAttachment } from '../lib/storage'
import { FilterSelect, type FilterOption } from '../components/FilterSelect'
import { AVAILABILITY_OPTIONS, EXCHANGE_FORMATS, FORMAT_NOTE, normalizeFormat } from '../lib/formats'

const ALL_CATEGORIES='All skill categories',ANY_AVAILABILITY='Any availability',ANY_FORMAT='Any supported format',ANY_LANGUAGE='Any language'
const types:MatchType[]=['Perfect Swap','Credit Match','Learning Partner','Project Helper']
const sortOptions:FilterOption[]=[{value:'Best match',label:'Best match'},{value:'Newest',label:'Newest'},{value:'Highest rated',label:'Highest rated'}]
const requestTypeOptions:FilterOption[]=(Object.keys(requestTypeLabel) as RequestKind[]).map(value=>({value,label:requestTypeLabel[value]}))
const composerFormatOptions:FilterOption[]=EXCHANGE_FORMATS.map(f=>({value:f,label:f}))
const typeIcon=(type:MatchType)=>type==='Perfect Swap'?<HeartHandshake/>:type==='Credit Match'?<Coins/>:type==='Learning Partner'?<UsersRound/>:<Target/>
function Skeletons(){return <div className="match-card-grid">{Array.from({length:6},(_,i)=><article className="match-skeleton" key={i}><span/><i/><i/><div/><b/></article>)}</div>}

export function DiscoverPage(){
  const{user}=useAuth(),fallback=user?.user_metadata?.full_name||localStorage.getItem('skillloop_preview_name')||'SkillLoop learner'
  const[current,setCurrent]=useState<SkillProfile>(()=>loadLocalProfile(user?.id,fallback)),[matches,setMatches]=useState<MatchResult[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const[search,setSearch]=useState(''),[type,setType]=useState('All'),[category,setCategory]=useState(ALL_CATEGORIES),[availability,setAvailability]=useState(ANY_AVAILABILITY),[format,setFormat]=useState(ANY_FORMAT),[language,setLanguage]=useState(ANY_LANGUAGE),[sort,setSort]=useState('Best match'),[filtersOpen,setFiltersOpen]=useState(false),[selected,setSelected]=useState<MatchResult|null>(null),[requesting,setRequesting]=useState<MatchResult|null>(null),[sent,setSent]=useState('')
  useEffect(()=>{let live=true;async function load(){try{const profile=user?.id?await loadRemoteProfile(user.id,fallback):loadLocalProfile(undefined,fallback);const candidates=await loadMatchCandidates(profile);if(live){setCurrent(profile);setMatches(buildMatches(profile,candidates));setLoading(false)}}catch(err){if(live){setError(err instanceof Error?err.message:'Could not load matches.');setLoading(false)}}}load();return()=>{live=false}},[user?.id,fallback])
  const categories=useMemo(()=>[ALL_CATEGORIES,...new Set(matches.map(match=>match.canHelpWith.category).filter(Boolean))],[matches])
  const languages=useMemo(()=>[ANY_LANGUAGE,...new Set(matches.flatMap(match=>match.languages))],[matches])
  const categoryOptions=useMemo<FilterOption[]>(()=>categories.map(value=>({value,label:value})),[categories])
  const availabilityOptions=useMemo<FilterOption[]>(()=>[{value:ANY_AVAILABILITY,label:ANY_AVAILABILITY},...AVAILABILITY_OPTIONS.map(value=>({value,label:value}))],[])
  const formatOptions=useMemo<FilterOption[]>(()=>[{value:ANY_FORMAT,label:ANY_FORMAT},...EXCHANGE_FORMATS.map(value=>({value,label:value}))],[])
  const languageOptions=useMemo<FilterOption[]>(()=>languages.map(value=>({value,label:value})),[languages])
  const visible=useMemo(()=>{let result=matches.filter(match=>{const text=`${match.name} ${match.canHelpWith.name} ${match.wantsHelpWith?.name||''}`.toLowerCase();return(!search||text.includes(search.toLowerCase()))&&(type==='All'||match.type===type)&&(category===ALL_CATEGORIES||match.canHelpWith.category===category)&&(availability===ANY_AVAILABILITY||match.availability.some(item=>item===availability))&&(format===ANY_FORMAT||match.canHelpWith.formats.some(f=>normalizeFormat(f)===format))&&(language===ANY_LANGUAGE||match.languages.includes(language))});if(sort==='Newest')result=[...result].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));if(sort==='Highest rated')result=[...result].sort((a,b)=>b.rating-a.rating);return result},[matches,search,type,category,availability,format,language,sort])
  const activeFilters=[type!=='All',category!==ALL_CATEGORIES,availability!==ANY_AVAILABILITY,format!==ANY_FORMAT,language!==ANY_LANGUAGE].filter(Boolean).length
  function clear(){setSearch('');setType('All');setCategory(ALL_CATEGORIES);setAvailability(ANY_AVAILABILITY);setFormat(ANY_FORMAT);setLanguage(ANY_LANGUAGE)}
  return <section className="discover-page">
    {sent&&<div className="hub-toast"><Check/>{sent}</div>}
    <header className="discover-header"><div><div className="eyebrow"><Sparkles/> Matches built around you</div><h1>Find the right person for your next step.</h1><p>Every score explains the skills, timing, and learning fit behind it.</p></div><div className="discover-profile-note"><span>{current.profileCompletion}%</span><div><strong>Match readiness</strong><small>{current.profileCompletion<70?'Add more profile detail for sharper results.':'Your profile gives us strong signals.'}</small></div><Link to="/profile" aria-label="Improve match readiness"><ArrowRight/></Link></div></header>
    <div className="discover-toolbar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people or skills…"/><kbd>⌘ K</kbd></label><button className="mobile-filter-button" onClick={()=>setFiltersOpen(true)}><Filter/> Filters {activeFilters>0&&<b>{activeFilters}</b>}</button><FilterSelect inline icon={<ArrowDownUp/>} label="Sort" value={sort} options={sortOptions} onChange={setSort}/></div>
    <div className="match-type-tabs"><button className={type==='All'?'active':''} onClick={()=>setType('All')}><Compass/> All matches <b>{matches.length}</b></button>{types.map(item=><button key={item} className={type===item?'active':''} onClick={()=>setType(item)}>{typeIcon(item)} {item}<b>{matches.filter(match=>match.type===item).length}</b></button>)}</div>
    <div className="discover-layout"><aside className={`match-filters ${filtersOpen?'open':''}`}><header><div><SlidersHorizontal/> <strong>Filters</strong></div><button onClick={()=>setFiltersOpen(false)} aria-label="Close filters"><X/></button></header>{activeFilters>0&&<button className="clear-filters" onClick={clear}>Clear all · {activeFilters}</button>}<FilterSelect label="Skill category" value={category} options={categoryOptions} onChange={setCategory}/><FilterSelect label="Availability" value={availability} options={availabilityOptions} onChange={setAvailability}/><FilterSelect label="Exchange format" value={format} options={formatOptions} onChange={setFormat}/><FilterSelect label="Language" value={language} options={languageOptions} onChange={setLanguage}/><div className="filter-tip"><Sparkles/><div><strong>Better in, better out.</strong><p>Add availability and learning style to improve your scores.</p><Link to="/profile">Improve profile</Link></div></div><button className="apply-filters" onClick={()=>setFiltersOpen(false)}>Show {visible.length} matches</button></aside>
      <main className="matches-main"><div className="matches-result-head"><div><strong>{loading?'Finding your people…':`${visible.length} thoughtful matches`}</strong><span>{activeFilters?`Filtered from ${matches.length} recommendations`:'Ranked by fit, not popularity'}</span></div>{!loading&&<span className="fresh-signal"><i/> Updated from your profile</span>}</div>
      {loading?<Skeletons/>:error?<div className="matches-empty"><span><Zap/></span><h2>Matching paused for a moment.</h2><p>{error}</p><button onClick={()=>window.location.reload()}>Try again</button></div>:visible.length?<div className="match-card-grid">{visible.map(match=><MatchCard key={match.id} match={match} onView={()=>setSelected(match)} onRequest={()=>setRequesting(match)}/>)}</div>:<div className="matches-empty"><span><Compass/></span><h2>We’re preparing your matches.</h2><p>{matches.length?'No people fit these filters yet. Clear a few filters to widen the loop.':'Add more skills to improve your results.'}</p><button onClick={matches.length?clear:()=>{window.location.href='/profile'}}>{matches.length?'Clear filters':'Improve my profile'}</button></div>}</main></div>
    {selected&&<MatchDetail match={selected} onClose={()=>setSelected(null)} onRequest={()=>{setSelected(null);setRequesting(selected)}}/>}
    {requesting&&<RequestComposer match={requesting} current={current} userId={user?.id} onClose={()=>setRequesting(null)} onSent={()=>{setRequesting(null);setSent(`Request sent to ${requesting.name}`);window.setTimeout(()=>setSent(''),2400)}}/>}
  </section>
}

function MatchCard({match,onView,onRequest}:{match:MatchResult;onView:()=>void;onRequest:()=>void}){return <article className="discover-match-card"><div className="match-score-ring" style={{'--score':`${match.score*3.6}deg`} as React.CSSProperties}><span><strong>{match.score}</strong><small>match</small></span></div><div className={`match-type-label type-${match.type.toLowerCase().replaceAll(' ','-')}`}>{typeIcon(match.type)} {match.type}</div><header><div className="discover-avatar">{match.avatarUrl?<img src={match.avatarUrl} alt=""/>:match.name.split(' ').map(v=>v[0]).join('').slice(0,2)}<i/></div><div><h2>{match.name}</h2><p><Star fill="currentColor"/> {match.rating||'New'} <span>({match.reviewCount} reviews)</span> · {match.completedSessions} sessions</p></div></header><div className="match-skill-pair"><span><small>CAN HELP YOU WITH</small><strong>{match.canHelpWith.name}</strong></span><HeartHandshake/><span><small>{match.wantsHelpWith?'WANTS TO LEARN':'EXCHANGE STYLE'}</small><strong>{match.wantsHelpWith?.name||match.type}</strong></span></div><div className="match-meta"><span><CalendarDays/> {match.availability[0]||'Flexible'}</span><span><Video/> {match.format}</span><span><Languages/> {match.languages.slice(0,2).join(', ')}</span></div><div className="reputation-row"><span><Award/> Trusted helper</span>{match.responseRate>=90&&<span><Zap/> Quick responder</span>}</div><footer><button onClick={onView}><UserRound/> View Profile</button><button onClick={onRequest}>Send Skill Request <ArrowRight/></button></footer></article>}

function MatchDetail({match,onClose,onRequest}:{match:MatchResult;onClose:()=>void;onRequest:()=>void}){return <div className="match-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="match-detail-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose} aria-label="Close match details"><X/></button><header><div className="detail-avatar">{match.name.split(' ').map(v=>v[0]).join('').slice(0,2)}<i/></div><div><div className={`match-type-label type-${match.type.toLowerCase().replaceAll(' ','-')}`}>{typeIcon(match.type)} {match.type}</div><h2>{match.name}</h2><p>{match.bio}</p></div><div className="detail-score"><strong>{match.score}%</strong><span>match score</span></div></header><div className="detail-body"><main><section><div className="detail-section-title"><Sparkles/><div><h3>Why this match works</h3><p>An explainable score based on your profiles.</p></div></div><div className="reason-list">{match.reasons.map(reason=><span key={reason}><Check/>{reason}</span>)}</div><div className="score-breakdown">{match.scoreParts.map(part=><div key={part.label}><span>{part.label}</span><i><b style={{width:`${part.points/part.max*100}%`}}/></i><strong>+{part.points}</strong></div>)}</div></section><section><div className="detail-section-title"><HeartHandshake/><div><h3>Suggested exchange</h3><p>A simple starting structure you can adjust.</p></div></div><div className="exchange-plan"><article><small>YOU LEARN</small><strong>{match.canHelpWith.name}</strong><span>{match.canHelpWith.level} helper</span></article><ArrowRight/><article><small>{match.wantsHelpWith?'YOU SHARE':'FORMAT'}</small><strong>{match.wantsHelpWith?.name||match.format}</strong><span>{match.type}</span></article></div></section><section><div className="detail-section-title"><MessageCircle/><div><h3>Suggested first message</h3><p>Personalized from the skills you have in common.</p></div></div><blockquote>“{match.message}”</blockquote></section></main><aside><div className="detail-quick"><h3>Best way to connect</h3><span><Video/><div><small>FORMAT</small><strong>{match.format}</strong></div></span><span><Clock3/><div><small>DURATION</small><strong>{match.preferredDuration} minutes</strong></div></span><span><Coins/><div><small>CREDIT COST</small><strong>{match.creditCost?`${match.creditCost} Skill Credit`:'No credit needed'}</strong></div></span></div><div className="detail-reputation"><h3>Profile signals</h3><span><Star fill="currentColor"/> {match.rating||'New'} rating</span><span><Zap/> {match.responseRate}% response rate</span><span><Check/> {match.completedSessions} sessions completed</span></div></aside></div><footer><button onClick={onClose}>Keep exploring</button><button className="button button-primary" onClick={onRequest}>Send Swap Request <ArrowRight/></button></footer></section></div>}

function RequestComposer({match,current,userId,onClose,onSent}:{match:MatchResult;current:SkillProfile;userId?:string;onClose:()=>void;onSent:()=>void}){
  const initialType:RequestKind=match.type==='Perfect Swap'?'direct_swap':match.type==='Learning Partner'?'learning_partner':match.type==='Project Helper'?'project_review':'credit_session'
  const[requestType,setRequestType]=useState<RequestKind>(initialType),[message,setMessage]=useState(match.message),[duration,setDuration]=useState(Number(current.duration)||30),[format,setFormat]=useState<string>(normalizeFormat(match.format)),[offeredSkillId,setOfferedSkillId]=useState(match.offeredSkillId||current.teach[0]?.id||''),[proposedTime,setProposedTime]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[attachmentUrl,setAttachmentUrl]=useState(''),[attachmentName,setAttachmentName]=useState(''),[attachmentUploading,setAttachmentUploading]=useState(false),[attachmentError,setAttachmentError]=useState('')
  const cost=creditCost(requestType,duration),offered=current.teach.find(skill=>skill.id===offeredSkillId)
  async function submit(e:FormEvent){e.preventDefault();if(requestType==='direct_swap'&&!offeredSkillId){setError('Choose the skill you can offer in return.');return}setSending(true);setError('');try{await createRequest({recipientId:match.id,partnerName:match.name,requestType,neededSkillId:match.canHelpWith.id,neededSkill:match.canHelpWith.name,offeredSkillId:requestType==='direct_swap'?offeredSkillId:undefined,offeredSkill:requestType==='direct_swap'?offered?.name:undefined,duration,format,message,attachmentUrl:attachmentUrl||undefined,proposedTime:proposedTime?new Date(proposedTime).toISOString():undefined},userId);onSent()}catch(err){setError(err instanceof Error?err.message:'Could not send the request.');setSending(false)}}
  async function onAttachment(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;setAttachmentError('');setAttachmentUploading(true);try{const{url}=await uploadAttachment(file,userId||'');setAttachmentUrl(url);setAttachmentName(file.name)}catch(err){setAttachmentError(err instanceof Error?err.message:'We couldn\'t upload that file. Please try again.')}finally{setAttachmentUploading(false)}}
  return <div className="match-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="request-composer phase5-composer"><header><span><HeartHandshake/></span><div><div className="eyebrow">Start an exchange</div><h2>Send a request to {match.name.split(' ')[0]}</h2></div><button onClick={onClose} aria-label="Close request form"><X/></button></header><form onSubmit={submit}>
    <FilterSelect label="Request type" value={requestType} options={requestTypeOptions} onChange={value=>setRequestType(value as RequestKind)}/>
    <div className="composer-grid"><label>Skill needed<input value={match.canHelpWith.name} readOnly/></label>{requestType==='direct_swap'&&<FilterSelect label="Skill you offer" value={offeredSkillId} options={[{value:'',label:'Choose your skill'},...current.teach.map(skill=>({value:skill.id||'',label:skill.name}))]} onChange={setOfferedSkillId}/>}</div>
    <div className="composer-grid"><FilterSelect label="Preferred format" value={format} options={composerFormatOptions} onChange={setFormat}/><label>Proposed time<input type="datetime-local" value={proposedTime} min={new Date().toISOString().slice(0,16)} onChange={e=>setProposedTime(e.target.value)}/></label></div>
    <p className="field-note">{FORMAT_NOTE[normalizeFormat(format)]}</p>
    <label>Suggested duration<div className="duration-options">{[15,30,60,90].map(value=><button type="button" className={duration===value?'active':''} onClick={()=>setDuration(value)} key={value}>{value} min</button>)}</div></label>
    <label>Your message<textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={20} maxLength={500} required/><small>{message.length}/500</small></label>
    <div className="composer-field"><span className="composer-field-label">Project attachment (optional)</span><div className="composer-attachment">{attachmentUrl?<a className="composer-attachment-link" href={attachmentUrl} target="_blank" rel="noreferrer"><Paperclip/> {attachmentName||'View attachment'}</a>:<span className="composer-attachment-empty"><Paperclip/> No file attached</span>}<label className={`button button-secondary${attachmentUploading?' is-loading':''}`}><Paperclip/> {attachmentUrl?'Replace file':'Attach file'}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif,application/pdf" onChange={onAttachment} disabled={attachmentUploading} hidden/></label></div>{attachmentError&&<small className="avatar-upload-error" role="alert">{attachmentError}</small>}</div>
    {error&&<div className="onboarding-error">{error}</div>}<div className="credit-preview"><Coins/><div><small>CREDIT COST</small><strong>{cost===0?'Free direct exchange':`${cost} Skill Credit${cost>1?'s':''}`}</strong><p>{cost?`Reserved only if ${match.name.split(' ')[0]} accepts.`:'No credits move for this exchange type.'}</p></div><span>{cost}</span></div><footer><button type="button" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={sending}>{sending?<LoaderCircle className="spin"/>:<MessageCircle/>}{sending?'Sending…':'Send Skill Request'}</button></footer>
  </form></section></div>}
