import { AlertTriangle, ArrowRight, CalendarDays, Check, Clock3, Coins, HeartHandshake, Inbox, LoaderCircle, MessageCircle, Paperclip, RefreshCw, Send, ShieldAlert, Sparkles, Video, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { cancelRequest, confirmExchange, loadRequests, requestTypeLabel, respondRequest, type ExchangeRequest, type RequestStatus } from '../lib/exchange'

const statuses:(RequestStatus|'all')[]=['all','pending','accepted','completed','declined','cancelled','disputed']
const date=(value?:string)=>value?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value)):'Time to be agreed'
export function RequestsPage(){
  const[requests,setRequests]=useState<ExchangeRequest[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[direction,setDirection]=useState<'incoming'|'outgoing'>('incoming'),[status,setStatus]=useState<RequestStatus|'all'>('all'),[working,setWorking]=useState(''),[notice,setNotice]=useState('')
  async function refresh(){setLoading(true);setError('');try{setRequests(await loadRequests())}catch(err){setError(err instanceof Error?err.message:'Could not load requests.')}finally{setLoading(false)}}
  useEffect(()=>{let live=true;loadRequests().then(data=>{if(!live)return;setRequests(data);const incoming=data.some(request=>request.direction==='incoming'),outgoing=data.some(request=>request.direction==='outgoing');if(!incoming&&outgoing)setDirection('outgoing')}).catch(err=>{if(live)setError(err instanceof Error?err.message:'Could not load requests.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[])
  const counts={incoming:requests.filter(r=>r.direction==='incoming').length,outgoing:requests.filter(r=>r.direction==='outgoing').length,accepted:requests.filter(r=>r.status==='accepted').length}
  const visible=useMemo(()=>requests.filter(r=>r.direction===direction&&(status==='all'||r.status===status)),[requests,direction,status])
  async function act(id:string,action:'accept'|'decline'|'cancel'){setWorking(id+action);setError('');try{if(action==='cancel')await cancelRequest(id);else await respondRequest(id,action);setNotice(action==='accept'?'Request accepted. A session and conversation are ready.':`Request ${action}d.`);await refresh();window.setTimeout(()=>setNotice(''),2500)}catch(err){setError(err instanceof Error?err.message:'That action could not be completed.')}finally{setWorking('')}}
  async function finish(sessionId:string,outcome:'confirm'|'dispute'){setWorking(sessionId+outcome);try{const result=await confirmExchange(sessionId,outcome);setNotice(result==='completed'?'Exchange completed. Credits are settled.':result==='disputed'?'Session sent for review.':'Confirmation saved. Waiting for the other member.');await refresh();window.setTimeout(()=>setNotice(''),2800)}catch(err){setError(err instanceof Error?err.message:'Could not update the session.')}finally{setWorking('')}}
  return <section className="requests-page">{notice&&<div className="hub-toast"><Check/>{notice}</div>}<header className="requests-header"><div><div className="eyebrow"><HeartHandshake/> Your exchanges</div><h1>Requests and sessions</h1><p>Move a thoughtful introduction into a completed learning exchange.</p></div><Link className="button button-primary" to="/discover"><Sparkles/> Find a new match</Link></header>
    <div className="request-overview"><article><span><Inbox/></span><div><small>INCOMING</small><strong>{counts.incoming}</strong></div></article><article><span><Send/></span><div><small>OUTGOING</small><strong>{counts.outgoing}</strong></div></article><article><span><CalendarDays/></span><div><small>ACTIVE SESSIONS</small><strong>{counts.accepted}</strong></div></article><article className="request-safety"><ShieldAlert/><div><strong>Credits stay protected.</strong><small>They settle only after both people confirm.</small></div></article></div>
    <div className="request-controls"><div className="direction-tabs"><button className={direction==='incoming'?'active':''} onClick={()=>setDirection('incoming')}>Incoming <b>{counts.incoming}</b></button><button className={direction==='outgoing'?'active':''} onClick={()=>setDirection('outgoing')}>Outgoing <b>{counts.outgoing}</b></button></div><div className="status-tabs">{statuses.map(item=><button key={item} className={status===item?'active':''} onClick={()=>setStatus(item)}>{item}</button>)}</div></div>
    {error&&<div className="request-error"><AlertTriangle/>{error}<button onClick={refresh}><RefreshCw/> Retry</button></div>}
    {loading?<div className="request-loading">{[1,2,3].map(item=><article key={item}><span/><div/><i/></article>)}</div>:visible.length?<div className="request-list">{visible.map(request=><RequestCard key={request.id} request={request} working={working} onAction={act} onFinish={finish}/>)}</div>:<div className="request-empty-page"><span>{direction==='incoming'?<Inbox/>:<Send/>}</span><h2>No {status==='all'?'':status} {direction} requests.</h2><p>{direction==='incoming'?'When someone values what you know, their request will appear here.':'Find a strong match and start with a personal message.'}</p><Link to="/discover">Discover matches <ArrowRight/></Link></div>}
  </section>}

function RequestCard({request,working,onAction,onFinish}:{request:ExchangeRequest;working:string;onAction:(id:string,action:'accept'|'decline'|'cancel')=>void;onFinish:(id:string,outcome:'confirm'|'dispute')=>void}){
  const busy=working.startsWith(request.id)||Boolean(request.session&&working.startsWith(request.session.id)),accepted=request.status==='accepted'&&request.session
  return <article className={`exchange-request-card status-${request.status}`}><header><div className="request-person"><span>{request.partnerName.split(' ').map(v=>v[0]).join('').slice(0,2)}<i/></span><div><small>{request.direction==='incoming'?'FROM':'TO'}</small><h2>{request.partnerName}</h2><p><Clock3/> Sent {date(request.createdAt)}</p></div></div><div className={`request-status status-${request.status}`}><i/>{request.status}</div></header><div className="request-exchange-summary"><article><small>{request.direction==='incoming'?'THEY NEED':'YOU NEED'}</small><strong>{request.neededSkill}</strong></article><HeartHandshake/><article><small>{request.offeredSkill?'OFFERED IN RETURN':'REQUEST TYPE'}</small><strong>{request.offeredSkill||requestTypeLabel[request.requestType]}</strong></article></div><div className="request-detail-row"><span><Video/><small>FORMAT</small><strong>{request.format}</strong></span><span><Clock3/><small>DURATION</small><strong>{request.duration} min</strong></span><span><CalendarDays/><small>PROPOSED</small><strong>{date(request.proposedTime)}</strong></span><span><Coins/><small>CREDIT COST</small><strong>{request.creditCost||'Free swap'}</strong></span></div><blockquote><MessageCircle/> <span>“{request.message}”</span></blockquote>{request.attachmentUrl&&<a className="request-attachment-link" href={request.attachmentUrl} target="_blank" rel="noreferrer"><Paperclip/> View project attachment</a>}
    {accepted&&<section className="accepted-session"><div className="session-heading"><span><CalendarDays/></span><div><small>SESSION CREATED</small><strong>{date(request.session?.startsAt)}</strong></div><b>{request.session?.status}</b></div><div className="confirmation-track"><span className={request.session?.learnerConfirmed?'done':''}><i>{request.session?.learnerConfirmed?<Check/>:1}</i>Learner confirmed</span><em/><span className={request.session?.helperConfirmed?'done':''}><i>{request.session?.helperConfirmed?<Check/>:2}</i>Helper confirmed</span></div><p>Credits remain pending until both people confirm the exchange was completed.</p></section>}
    {request.status==='completed'&&<div className="review-prompt"><Sparkles/><div><strong>Exchange complete. Build trust while it’s fresh.</strong><span>Your review prompt is ready.</span></div>{request.session?.id&&<Link to={`/sessions/${request.session.id}`}>Review exchange <ArrowRight/></Link>}</div>}
    <footer>{request.direction==='incoming'&&request.status==='pending'&&<><button className="request-decline" disabled={busy} onClick={()=>onAction(request.id,'decline')}><X/> Decline</button><button className="button button-primary" disabled={busy} onClick={()=>onAction(request.id,'accept')}>{busy?<LoaderCircle className="spin"/>:<Check/>} Accept request</button></>}{request.direction==='outgoing'&&request.status==='pending'&&<><span>Waiting for {request.partnerName.split(' ')[0]} to respond.</span><button className="request-decline" disabled={busy} onClick={()=>onAction(request.id,'cancel')}><X/> Cancel request</button></>}{accepted&&<><button className="request-dispute" disabled={busy} onClick={()=>onFinish(request.session!.id,'dispute')}><AlertTriangle/> Report an issue</button><button className="button button-primary" disabled={busy} onClick={()=>onFinish(request.session!.id,'confirm')}>{busy?<LoaderCircle className="spin"/>:<Check/>} Confirm completed</button></>}{['declined','cancelled','disputed'].includes(request.status)&&<span>This exchange is closed. Its history remains visible for clarity.</span>}</footer></article>}
