import { ArrowDownLeft, ArrowRight, ArrowUpRight, Check, Clock3, Coins, Gift, HeartHandshake, History, ListFilter, LoaderCircle, RefreshCw, RotateCcw, ShieldCheck, Sparkles, Video } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { loadWallet, type CreditTransaction, type Wallet } from '../lib/exchange'
import { FilterSelect, type FilterOption } from '../components/FilterSelect'

const filterOptions:FilterOption[]=[{value:'all',label:'All activity'},{value:'earned',label:'Earned'},{value:'spent',label:'Spent'},{value:'bonus',label:'Bonuses'},{value:'refund',label:'Refunds'}]

const empty:Wallet={available:0,pending:0,earned:0,spent:0,refunded:0,transactions:[]}
const icon=(item:CreditTransaction)=>item.type==='earned'?<ArrowDownLeft/>:item.type==='spent'?<ArrowUpRight/>:item.type==='refund'?<RotateCcw/>:<Gift/>
export function WalletPage(){const[wallet,setWallet]=useState<Wallet>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all');useEffect(()=>{loadWallet().then(setWallet).catch(err=>setError(err instanceof Error?err.message:'Could not load wallet.')).finally(()=>setLoading(false))},[]);const visible=useMemo(()=>wallet.transactions.filter(item=>filter==='all'||item.type===filter),[wallet.transactions,filter]);return <section className="skill-wallet-page"><header className="wallet-page-header"><div><div className="eyebrow"><Coins/> Skill Credit economy</div><h1>My Skill Wallet</h1><p>Every credit represents time someone gave and knowledge someone shared.</p></div><Link className="button button-primary" to="/discover"><Sparkles/> Spend a credit</Link></header>
  <div className="wallet-hero"><div className="wallet-balance"><span><Coins/></span><div><small>AVAILABLE TO SPEND</small><strong>{loading?'—':wallet.available}</strong><p>Skill Credits</p></div><i/><i/></div><div className="wallet-state-grid"><article><span className="earned"><ArrowDownLeft/></span><div><small>LIFETIME EARNED</small><strong>{wallet.earned}</strong></div></article><article><span className="spent"><ArrowUpRight/></span><div><small>LIFETIME SPENT</small><strong>{wallet.spent}</strong></div></article><article><span className="pending"><Clock3/></span><div><small>PENDING</small><strong>{wallet.pending}</strong></div></article><article><span className="refunded"><RotateCcw/></span><div><small>REFUNDED</small><strong>{wallet.refunded}</strong></div></article></div></div>
  <div className="wallet-protection"><ShieldCheck/><div><strong>Protected until both people confirm.</strong><p>Accepted-session credits move into escrow. They become available to the helper only after dual confirmation.</p></div></div>
  <div className="wallet-content"><main><div className="wallet-section-head"><div><History/><span><h2>Transaction history</h2><p>A transparent record of every credit movement.</p></span></div><FilterSelect inline icon={<ListFilter/>} label="Show" value={filter} options={filterOptions} onChange={setFilter}/></div>{loading?<div className="wallet-loading"><LoaderCircle className="spin"/> Loading your wallet…</div>:error?<div className="wallet-error"><RefreshCw/><p>{error}</p></div>:visible.length?<div className="transaction-list">{visible.map(item=><article key={item.id}><span className={`transaction-icon ${item.type}`}>{icon(item)}</span><div><strong>{item.reason}</strong><small>{new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(item.createdAt))} · Balance {item.balanceAfter}</small></div><b className={item.amount>0?'positive':'negative'}>{item.amount>0?'+':''}{item.amount}</b><em className={`transaction-status ${item.status}`}>{item.status}</em></article>)}</div>:<div className="wallet-empty"><Coins/><h3>Your credit story starts here.</h3><p>Help someone today to earn your first Skill Credit.</p></div>}</main><aside><h2>Ways to earn credits</h2><p>Generosity keeps the loop moving.</p><div className="earn-cards"><article><span><Video/></span><div><strong>Complete a 30-minute session</strong><p>Help someone learn and earn 1 credit after both people confirm.</p></div><b>+1</b></article><article><span><HeartHandshake/></span><div><strong>Offer a project review</strong><p>Longer reviews can earn more depending on duration.</p></div><b>+1–3</b></article><article><span><Sparkles/></span><div><strong>Direct skill swap</strong><p>Trade help both ways without spending any credits.</p></div><b>Free</b></article></div><Link to="/discover">Find someone to help <ArrowRight/></Link><div className="wallet-rule"><Check/><span><strong>Simple rule</strong><p>30 minutes of confirmed help equals one Skill Credit.</p></span></div></aside></div></section>}
