import { useState, type FormEvent } from 'react'
import { Ban, Check, Flag, LoaderCircle, ShieldAlert, X } from 'lucide-react'
import { reportReasons, submitSafetyReport, toggleUserBlock, type SafetyTarget } from '../lib/safety'
import { FilterSelect } from './FilterSelect'

const reasonOptions=[{value:'',label:'Select a reason'},...reportReasons.map(r=>({value:r,label:r}))]

export function SafetyActions({targetType,targetId,userId,compact=false}:{targetType:SafetyTarget;targetId:string;userId?:string;compact?:boolean}){
  const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[reason,setReason]=useState('')
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!reason){setError('Please choose a reason for this report.');return}const data=new FormData(event.currentTarget);setSaving(true);setError('');try{await submitSafetyReport(targetType,targetId,reason,String(data.get('details')));setNotice('Report sent to the safety team.');setOpen(false);setReason('')}catch(err){setError(err instanceof Error?err.message:'Could not send this report.')}finally{setSaving(false)}}
  async function block(){if(!userId)return;setSaving(true);try{const blocked=await toggleUserBlock(userId);setNotice(blocked?'User blocked. They can no longer contact you.':'User unblocked.')}catch(err){setError(err instanceof Error?err.message:'Could not update this block.')}finally{setSaving(false)}}
  return <div className={`safety-actions ${compact?'compact':''}`}><button type="button" onClick={()=>setOpen(true)} aria-label={`Report ${targetType}`}><Flag/>{!compact&&'Report'}</button>{userId&&<button type="button" onClick={block} disabled={saving} aria-label="Block this user"><Ban/>{!compact&&'Block'}</button>}{notice&&<span className="safety-inline-notice"><Check/>{notice}<button type="button" onClick={()=>setNotice('')} aria-label="Dismiss safety notice"><X/></button></span>}{open&&<div className="match-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><form className="safety-report-modal" onSubmit={submit}><header><span><ShieldAlert/></span><div><small>CONFIDENTIAL SAFETY REPORT</small><h2>Tell us what happened.</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close report form"><X/></button></header><p>Reports are reviewed by SkillLoop administrators. The other person will not see who submitted it.</p><FilterSelect label="Reason" value={reason} options={reasonOptions} onChange={setReason}/><label>What should the safety team know?<textarea name="details" required minLength={10} maxLength={2000} placeholder="Add the context needed to review this fairly."/></label>{error&&<div className="onboarding-error">{error}</div>}<footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Flag/>} Submit report</button></footer></form></div>}</div>
}
